// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwsASZzNI8BHQ1_3UUCIwt30RdapF3cW4',
    appId: '1:274987690634:web:b53ee2876977033728db73',
    messagingSenderId: '274987690634',
    projectId: 'nutricare-2bb9e',
    authDomain: 'nutricare-2bb9e.firebaseapp.com',
    databaseURL: 'https://nutricare-2bb9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutricare-2bb9e.appspot.com',
    measurementId: 'G-RBTWE00NSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD6i0d8b3Ob85Y-w5AE1A6-EExtGYA0mM',
    appId: '1:274987690634:android:d3a6da5f8104301b28db73',
    messagingSenderId: '274987690634',
    projectId: 'nutricare-2bb9e',
    databaseURL: 'https://nutricare-2bb9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutricare-2bb9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8PMV7C5nwicWP9VyPcXuNwpq7dAwAko',
    appId: '1:274987690634:ios:8fc4769b1867687e28db73',
    messagingSenderId: '274987690634',
    projectId: 'nutricare-2bb9e',
    databaseURL: 'https://nutricare-2bb9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutricare-2bb9e.appspot.com',
    iosBundleId: 'com.example.nutricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa8PMV7C5nwicWP9VyPcXuNwpq7dAwAko',
    appId: '1:274987690634:ios:8fc4769b1867687e28db73',
    messagingSenderId: '274987690634',
    projectId: 'nutricare-2bb9e',
    databaseURL: 'https://nutricare-2bb9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutricare-2bb9e.appspot.com',
    iosBundleId: 'com.example.nutricare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwsASZzNI8BHQ1_3UUCIwt30RdapF3cW4',
    appId: '1:274987690634:web:d3167502a48c7b0228db73',
    messagingSenderId: '274987690634',
    projectId: 'nutricare-2bb9e',
    authDomain: 'nutricare-2bb9e.firebaseapp.com',
    databaseURL: 'https://nutricare-2bb9e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutricare-2bb9e.appspot.com',
    measurementId: 'G-VCD7M8J5Y3',
  );
}
